// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();
const path = require("path"); 
const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });


  const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, "uploads/"),
  filename: (req, file, cb) => {
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const upload2 = multer({ storage });


router.post("/login", dataController.login);
router.post("/forgetPassword", dataController.forgetPassword);
router.post('/verify-otp', dataController.verifyOtp);
router.post("/signup", dataController.signUp);
router.post("/city", dataController.getCity)
router.post("/variant", dataController.getvariant)
router.post("/uom", dataController.getuom)
router.post("/country", dataController.getCountry)
router.post("/state", dataController.getState)
router.post("/status", dataController.getStatus)
router.post("/Shift", dataController.getShift)
router.post("/Transaction", dataController.getTransaction)
router.post("/gender", dataController.getGender)
router.post("/Loginorout", dataController.getLoginorout)
router.get("/", dataController.getAllData)
router.post("/add", upload.fields([ { name: 'company_logo', maxCount: 1 }, { name: 'authorisedSignatur', maxCount: 1 } ]),dataController.addData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.get ("/userData", dataController.getAlluserData)
router.get("/WareHouseData",dataController.getAllWareHouseData)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/userdelete", dataController.UserdeleteData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.get("/attrihdrdata",dataController.getAllattributehdrData)
router.post("/addattriData",dataController.addattrihdrData)
router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.get("/hdrcode", dataController.gethdrcode)
router.post("/delPer", dataController.getDeletepermission)
router.post("/regbrand", dataController.getregisterbrand)
router.post("/ourbrand", dataController.getourbrand)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.get("/VendorHdrData",dataController.getAllVendorHdrData)
router.post("/addVendorHdrData",dataController.addVendorHdrData)
router.get("/VendorDetData", dataController.getAllVendorDetData)
router.post("/addVendorDetData",dataController.addVendorDetData)
router.post("/updvendordetData",dataController.updvendordetData)
router.post("/deleteVendorData",dataController.VendordeleteData)
router.post("/vendorcode",dataController.getvendorcode)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.get("/usercode",dataController.getUsercode)
router.post("/Usertype", dataController.getUsertype)
router.get("/Companyno",dataController.getCompanyno)
router.get("/locationno",dataController.getLocationno)
router.post("/paytype", dataController.getPaytype)
router.post("/purchasetype", dataController.getPurchasetype)
router.post("/salestype", dataController.getSalestype)
router.post("/ordertype", dataController.getordertype)
router.post("/vendorcodename", dataController.getVendorcodename)
router.post("/roleid", dataController.getroleid)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/location_no",dataController.locationsaveEditedData)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/vendorsearchdata",dataController.getvendorSearchdata)
router.post("/PartyCode",dataController.getPartyCode)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/transactiontype",dataController.gettranstype)
router.get("/Numberseries",dataController.getAllNumberseries)
router.post("/addNumberseries",dataController.addNumberseries)
router.post("/numberseriessearchdata",dataController.getnumberseriessearchdata)
router.post("/saveEditedNumberseriesData",dataController.saveEditedNumberseriesData)
router.post("/screentype",dataController.getscreentype)
router.post("/Passwords",dataController.Passwords)
router.post("/numberseriesdeleteData",dataController.numberseriesdeleteData)
router.post("/getusercompany",dataController.getusercompany)
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.get("/userscreenmap", dataController.getAlluserscreenmap)
router.post("/adduserscreenmap",dataController.adduserscreenmap)
router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/customerhdr", dataController.getAllcustomerhdr)
router.post("/addcustomerhdr",dataController.addcustomerhdr)
router.get("/CustomerDetData", dataController.getAllCustomerDetData)
router.post("/addCustomerDetData",dataController.addCustomerDetData)
router.post("/updcustomerdetData",dataController.updcustomerdetData)
router.post("/customercode",dataController.getcustomercode)
router.post("/customerSearchdata",dataController.customerSearchdata)
router.post("/customerdeleteData",dataController.customerdeleteData)
router.get("/openbalance", dataController.getAllopenbalance)
router.post("/addopenbalance",dataController.addopenbalance)
router.post("/openbalsaveEditedData",dataController.openbalsaveEditedData)
router.post("/openingbalancedeleteData",dataController.openingbalancedeleteData)
router.post("/getopeningbalancedata",dataController.getopeningbalanceSearchdata)
router.post("/getCustomerCode",dataController.getCustomerCode)
router.post("/getCustomerSearchdata",dataController.getCustomerSearchdata)
router.post("/getUserPermission",dataController.getUserPermission)
router.post("/addjournal",dataController.addjournal)
router.post("/getjournalSearch",dataController.getjournalSearch)
router.post("/saveEditjournal",dataController.saveEditjournal)
router.post("/deletejournal",dataController.deletejournal)
router.get("/getwarehousecode", dataController.getwarehousecode)
router.post("/facereg", dataController.facereg);
router.post("/addUserAccGrp",dataController.addUserAccGrp)
router.post("/getsearchUserAccGrp", dataController.getsearchUserAccGrp);
router.post("/updUserAccGrp", dataController.updUserAccGrp);
router.post("/deleteUserAccGrp",dataController.deleteUserAccGrp)
router.post("/addAccountName",dataController.addAccountName)
router.post("/getAccNameSearch",dataController.getAccNameSearch)
router.post("/updateAccName",dataController.updateAccName)
router.post("/AccNameDelete",dataController.AccNameDelete)
router.get("/AllAccNameData",dataController.getAllAccNameData)
router.get("/getDateRange",dataController.getDateRange)
router.post("/getUsercodename",dataController.getUsercodename)
router.post("/getAccountCode",dataController.getAccountCode)
router.post("/addbankAccount",upload.single('bank_paymentQRCode'),dataController.addbankAccount)
router.post("/getacctype",dataController.getacctype)
router.post("/updatebankAcc",dataController.updatebankAcc)
router.post("/getbankaccSearch",dataController.getbankaccSearch)
router.post("/getofftype",dataController.getofftype)
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/UserRole",dataController.getUserRole)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/getEmptype", dataController.getEmptype)
router.post("/Condition", dataController.getCondition)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/CompanyUpdate",upload.fields([ { name: 'company_logo', maxCount: 1 }, { name: 'authorisedSignatur', maxCount: 1 }]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/NumberSeriesUpdate", dataController.NumberSeriesUpdate)
router.post("/VendorUpdate", dataController.VendorUpdate)
router.post("/CustomerUpdate", dataController.CustomerUpdate)
router.post("/BankAccountUpdate",upload.single('bank_paymentQRCode'), dataController.BankAccountUpdate)
router.post("/COAUpdate",dataController.COAUpdate) // charts of Accounts
router.post("/UserAccGrpUpdate",dataController.UserAccGrpUpdate) 
router.post("/getEvent", dataController.getEvent)
router.post("/addSalaryDetails",dataController.addSalaryDetails)
router.get("/allSalaryDetailsData",dataController.allSalaryDetailsData)
router.post("/deleteSalaryDetails",dataController.deleteSalaryDetails)
router.post("/updateSalaryDetails",dataController.updateSalaryDetails)
router.post("/getsiblings",dataController.getsiblings)
router.post("/getKids",dataController.getkids)
router.post("/getMartial",dataController.getMartial)
router.post("/addDailyattendance",dataController.addDailyattendance)
router.post("/getSalaryType",dataController.getSalaryType)
router.post("/getPayscale",dataController.getPayscale)
router.post("/getLoanID",dataController.getLoanID)
router.post("/getDocumentType",dataController.getDocumentType)
router.post("/getCustomerDetails",dataController.getCustomerDetails)
router.post("/getrelation",dataController. getrelation)
router.post("/getannoncementtype",dataController. getannoncementtype)
router.post("/getAnnouncementDetail",dataController. getAnnouncementDetail)
router.post("/getAnnouncement_Msg",dataController. getAnnouncement_Msg)
router.get("/getAnnouncementDetail",dataController.getAnnouncement)
router.post("/getcompanyshift",dataController.getcompanyshift)
router.post("/getOverallTAX",dataController.getOverallTAX)
router.post("/getInvocieType",dataController.getInvocieType)
router.post("/getUsercodenameBank",dataController.getUsercodenameBank)
router.post("/getVendorDetails",dataController.getVendorDetails)
router.post("/getFinancialDetailsSearchCretria",dataController.getFinancialDetailsSearchCretria)
router.post("/Terms",dataController.TermsDC)
router.post("/TermsQO",dataController.TermsQO)
router.post("/TermsPO",dataController.TermsPO)
router.post("/TermsTI",dataController.TermsTI)
router.post("/getLeaveType",dataController.getLeaveType)
router.post("/getSelectSlot",dataController.getSelectSlot)
router.post("/getDashBoardType",dataController.getDashBoardType)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getType",dataController.getType)
router.post("/getAccrual",dataController.getAccrual)
router.post("/getExceedLeave",dataController.getExceedLeave)
router.post("/getLeaveReason",dataController.getLeaveReason)
router.post("/getAnnouncement",dataController.getAnnouncement)
router.post("/DailyattendanceandTime",dataController.DailyattendanceandTime)
router.post("/getCustomerCodeDrop",dataController.getCustomerCodeDrop)
router.post("/getPendingStatus",dataController.getPendingStatus)
router.post("/getdefCustomer",dataController.getdefCustomer)
router.post("/getSalesMode",dataController.getSalesMode)
router.post("/getPurchaseAnalysis",dataController.getPurchaseAnalysis)
router.post("/addDailyLogin",dataController.addDailyLogin)
router.post("/addDailyTask", upload.array('Files', 10), dataController.addDailyTask);
router.post("/delDailyTask",dataController.delDailyTask)
router.post("/getTaskstatus",dataController.getTaskstatus)
router.post("/PendingCustomer",dataController.PendingCustomer)
router.post("/updateBankAccount",upload.single('bank_paymentQRCode'),dataController.updateBankAccount)
router.post("/getPriority",dataController.getPriority)
router.post("/getTaskDetailReport",dataController.getTaskDetailReport)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/DailyLogin",dataController.DailyLogin)
router.post("/DailyLogOUT",dataController.DailyLogOUT)
router.get("/GetCC",dataController.GetCC) //get company code dropdown
router.post("/InsertStockVal",dataController.InsertStockVal)
router.post("/updateStockVal",dataController.updateStockVal)
router.post("/updateStockValStatus",dataController.updateStockValStatus)
router.post("/deleteStockValue",dataController.deleteStockValue)
router.post("/StockSC",dataController.StockSC)
router.post("/getAnnouncementDuration",dataController.getAnnouncementDuration)
router.post("/AddFileAttachment", upload.array('Files', 10), dataController.AddFileAttachment);
router.post("/getboolean", dataController.getboolean)
router.post("/getDocument",dataController.getDocument)
router.post("/sendAutoMail",dataController.sendAutoMail)
router.post("/updateRoleRights",dataController.updateRoleRights)
router.post("/termsandCondition",dataController.termsandCondition)
router.post("/customerCodeDropdown",dataController.customerCodeDropdown)
router.post("/getLockType", dataController.getLockType)
router.post("/vendorCodeDropdown",dataController.vendorCodeDropdown)
router.post("/getPrint",dataController.getPrint)
router.post("/getcopies",dataController.getcopies)
router.post("/WeekOff",dataController.WeekOff)
router.post("/addCRMClient",dataController.addCRMClient)
router.post("/updateCRMClient",dataController.updateCRMClient)
router.post("/deleteCRMClient",dataController.deleteCRMClient)
router.post("/getCRMClient",dataController.getCRMClient)
router.post("/addCRMContacts",upload.single('Image'),dataController.addCRMContacts)
router.post("/updateCRMContacts",dataController.updateCRMContacts)
router.post("/deleteCRMContacts",dataController.deleteCRMContacts)
router.post("/getCRMContacts",dataController.getCRMContacts)
router.get("/getCRMContactName",dataController.getCRMContactName)
router.post("/GenerateEmployee",dataController.GenerateEmployee)
router.post("/GetUserCheckIN",dataController.GetUserCheckIN)
router.post("/getLeaveStatus",dataController.getLeaveStatus)
router.post("/getCheckInStatus",dataController.getCheckInStatus)
router.post("/GetPaymentMode", dataController.GetPaymentMode)
router.post("/GetPaymentType", dataController.GetPaymentType)
router.post("/uploadImage", upload2.single("image"), dataController.uploadImages);
router.post("/Client_PaymentInsert", dataController.Client_PaymentInsert)
router.post("/Client_PaymentUpdate", dataController.Client_PaymentUpdate)
router.post("/Client_PaymentDelete", dataController.Client_PaymentDelete)
router.post("/Client_PaymentLoopUpdate", dataController.Client_PaymentLoopUpdate)
router.post("/Client_PaymentLoopDelete", dataController.Client_PaymentLoopDelete)
router.post("/GetClient_PaymentData", dataController.GetClient_PaymentData)
router.post("/GetClient_PaymentDataSearch", dataController.GetClient_PaymentDataSearch)
router.post("/CRM_ContactInfoInsert", upload.single('Image'), dataController.CRM_ContactInfoInsert)
router.post("/CRM_ContactInfoUpdate", upload.single('Image'), dataController.CRM_ContactInfoUpdate)
router.post("/CRM_ContactInfoDelete", dataController.CRM_ContactInfoDelete)
router.post("/ClientPaymentExcel", dataController.getClientPaymentExcel)
router.post("/ContactInfoCompanyName", dataController.CRM_ContactInfoCompanyName)
router.post("/CompanySearch", dataController.CompanySearch)
router.post("/CRM_SourceInsert", dataController.CRM_SourceInsert)
router.post("/CRM_SalesPersonMasterInsert", dataController.CRM_SalesPersonMasterInsert)
router.post("/CRM_SalesPersonMasterUpdate", dataController.CRM_SalesPersonMasterUpdate)
router.post("/CRM_SalesPersonMasterDelete", dataController.CRM_SalesPersonMasterDelete)
router.post("/defaultCompanyNames", dataController.defaultCompanyNames)
router.post("/defaultContactsName", dataController.defaultContactsName)
router.post("/companyToContact", dataController.companyToContact)
router.post("/contactToCompany", dataController.contactToCompany)
router.post("/getDateRangeCRM", dataController.getDateRangeCRM)
router.post("/CRM_NewCompanyInsert", dataController.CRM_NewCompanyInsert)
router.post("/getNewCompany", dataController.getNewCompany)
router.post("/updateNewCompanyStage", dataController.updateNewCompanyStage)
router.post("/CRM_NewCompanyDelete", dataController.CRM_NewCompanyDelete)
router.post("/getOpportunityDetails", dataController.getOpportunityDetails)
router.post("/CRM_NewCompanyUpdate", dataController.CRM_NewCompanyUpdate)
router.post("/CRM_SalesTeam_DetailsInsert", dataController.CRM_SalesTeam_DetailsInsert)
router.post("/CRM_SalesTeam_DetailsUpdate", dataController.CRM_SalesTeam_DetailsUpdate)
router.post("/CRM_SalesTeam_DetailsDelete", dataController.CRM_SalesTeam_DetailsDelete)
router.post("/CRM_ActivityInsert",upload.single('Attachments'), dataController.CRM_ActivityInsert)
router.post("/CRM_ActivityUpdate", dataController.CRM_ActivityUpdate)
router.post("/CRM_ActivityDelete", dataController.CRM_ActivityDelete)
router.post("/getCustomerDropdown", dataController.getCustomerDropdown)
router.post("/updateNewCompanyPeriority", dataController.updateNewCompanyPeriority)
router.post("/GetSalesperson", dataController.GetSalesperson)
router.post("/CRM_ActivityDelete", dataController.CRM_ActivityDelete)
router.post("/CRM_AddContactInsert", dataController.CRM_AddContactInsert)
router.post("/CRM_AddContactUpdate", dataController.CRM_AddContactUpdate)
router.post("/CRM_AddContactDelete", dataController.CRM_AddContactDelete)
router.post("/CRM_LogNoteInsert", dataController.CRM_LogNoteInsert)
router.post("/CRM_LogNoteUpdate", dataController.CRM_LogNoteUpdate)
router.post("/CRM_LogNoteDelete", dataController.CRM_LogNoteDelete)
router.post("/CRM_MeetingSubjectInsert", dataController.CRM_MeetingSubjectInsert)
router.post("/CRM_MeetingSubjectUpdate", dataController.CRM_MeetingSubjectUpdate)
router.post("/CRM_MeetingSubjectDelete", dataController.CRM_MeetingSubjectDelete)
router.post("/CRM_CampaignInsert", dataController.CRM_CampaignInsert)
router.post("/CRM_CampaignUpdate", dataController.CRM_CampaignUpdate)
router.post("/CRM_CampaignDelete", dataController.CRM_CampaignDelete)
router.post("/CRM_MediumInsert", dataController.CRM_MediumInsert)
router.post("/CRM_MediumUpdate", dataController.CRM_MediumUpdate)
router.post("/CRM_MediumDelete", dataController.CRM_MediumDelete)
router.post("/CRM_SalesPurchaseInserts", dataController.CRM_SalesPurchaseInsert)
router.post("/CRM_SalesPurchaseUpdate", dataController.CRM_SalesPurchaseUpdate)
router.post("/CRM_SalesPurchaseDelete", dataController.CRM_SalesPurchaseDelete)
router.post("/CRM_NewEventInsert", dataController.CRM_NewEventInsert)
router.post("/CRM_NewEventUpdate", dataController.CRM_NewEventUpdate)
router.post("/CRM_NewEventDelete", dataController.CRM_NewEventDelete)
router.post("/CRM_MessageInsert", dataController.CRM_MessageInsert)
router.post("/CRM_MessageUpdate", dataController.CRM_MessageUpdate)
router.post("/CRM_MessageDelete", dataController.CRM_MessageDelete)
router.post("/GetSalesperson", dataController.GetSalesperson)
router.post("/GetSalespersonALL", dataController.GetSalespersonALL)
router.post("/salesPersonDropdown", dataController.salesPersonDropdown)
router.post("/GetDataContactInfo", dataController.GetDataContactInfo)
router.post("/GetDataContact", dataController.GetDataContact)
router.post("/getContactEmail", dataController.getContactEmail)
router.post("/getContacts", dataController.getContacts)
router.post("/getContactsDetails", dataController.getContactsDetails)
router.post("/getSource", dataController.getSource)
router.post("/getMedium", dataController.getMedium)
router.post("/CRM_LogNoteGet", dataController.CRM_LogNoteGet)
router.post("/searchSource", dataController.searchSource)
router.post("/mediumSearch", dataController.mediumSearch)
router.post("/CampaignSearch", dataController.CampaignSearch)
router.post("/SearchSalesperson", dataController.SearchSalesperson)
router.post("/getCampaign", dataController.getCampaign)
router.post("/CRM_Tag_MasterInsert", dataController.CRM_Tag_MasterInsert)
router.post("/CRM_Tag_MasterUpdate", dataController.CRM_Tag_MasterUpdate)
router.post("/CRM_Tag_MasterDelete", dataController.CRM_Tag_MasterDelete)
router.post("/CRM_SalesTeam_HDRInsert", dataController.CRM_SalesTeam_HDRInsert)
router.post("/CRMClientSearch", dataController.CRMClientSearch)
router.post("/GetTeam", dataController.GetTeam)
router.post("/GetSalesTeam", dataController.GetSalesTeam)
router.post("/GetTeamName", dataController.GetTeamName)
router.post("/GetActivity", dataController.GetActivity)
router.post("/GetContactClient", dataController.GetContactClient)
router.post("/GetContactInfo", dataController.GetContactInfo)
router.post("/activitySearch", dataController.activitySearch)
router.post("/TagSearch", dataController.TagSearch)
router.post("/getTagName", dataController.getTagName)
router.post("/GetActivityAll", dataController.GetActivityAll)
router.post("/GetContactInfoData", dataController.GetContactInfoData)
router.post("/GetContactInfoDetails", dataController.GetContactInfoDetails)
router.post("/GetCompanyMonth", dataController.GetCompanyMonth)
router.post("/SalesTeamSearch", dataController.SalesTeamSearch)
router.post("/Forecastsearch", dataController.Forecastsearch)
router.post("/CRM_CompanyDateUpdate", dataController.CRM_CompanyDateUpdate)
router.post("/CRM_CompanySearch", dataController.CRM_CompanySearch)
router.post("/ContactSearch", dataController.ContactSearch)
router.post("/CRM_MarkUP", dataController.CRM_MarkUP)
router.post("/SalesTeamChart", dataController.SalesTeamChart)
router.post("/Pipelinechart", dataController.Pipelinechart)
router.post("/CRM_Lose_Insert", dataController.CRM_Lose_Insert)
router.post("/CRM_Lose_Select", dataController.CRM_Lose_Select)
router.post("/PipelineDetailChart", dataController.PipelineDetailChart)
router.post("/ActivityChart", dataController.ActivityChart)
router.post("/getDomain", dataController.getDomain)
router.post("/GetAllMeeting", dataController.GetAllMeeting)
router.post("/SalesTeamDetailChart", dataController.SalesTeamDetailChart)
router.post("/GetActive", dataController.GetActive)
router.post("/GetRevenue",dataController.GetRevenue)
router.post("/GetAllEvent",dataController.GetAllEvent)
router.post("/CRMSalesTeamUpdateGrid", dataController.CRMSalesTeamUpdateGrid)
router.post("/CRM_LoseSC",dataController.CRM_LoseSC)
router.post("/ActivityDetailChart",dataController.ActivityDetailChart)
router.get("/CRM_PV",dataController.CRM_PV)
router.post("/GetCalendarEvent",dataController.GetCalendarEvent)
router.post("/CRM_Lose_Delete",dataController.CRM_Lose_Delete)
router.post("/CRM_SalesTeam_HDRUpdate",dataController.CRM_SalesTeam_HDRUpdate)
router.post("/getCompanyData",dataController.getCompanyData)
router.post("/getCompanyMappingData",dataController.getCompanyMappingData)
router.post("/getLocationData",dataController.getLocationData)
router.post("/getRoleData",dataController.getRoleData)
router.post("/getRoleMappingData",dataController.getRoleMappingData)
router.post("/getRoleRightsData",dataController.getRoleRightsData)
router.post("/getUserData",dataController.getUserData)
router.post("/getAttributeData",dataController.getAttributeData)
router.post("/getDefaultScreens",dataController.getDefaultScreens)
router.post("/userSettingsInsert",dataController.userSettingsInsert)
router.post("/getUserSettings",dataController.getUserSettings)
router.post("/getDefaultUserCompany",dataController.getDefaultUserCompany)

module.exports = router;
     
